
name: Release
on:
  workflow_dispatch:
  push:
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - add-arm-build-target
  # for testing:
  # pull_request:
  #   branches:
  #     - main

env:
  TWINE_PASSWORD: ${{secrets.TWINE_PASSWORD}}
  TWINE_USERNAME: ${{secrets.TWINE_USERNAME}}
  RUSTFLAGS: -C target-cpu=k8

jobs:
  release_manylinux-86:
    name: Release manylinux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-path: [ 'cp39-cp39' ]
    container: quay.io/pypa/manylinux2014_x86_64:latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: yum install -y libffi libffi-devel openssl openssl-devel
      - run: /opt/python/${{ matrix.python-path }}/bin/python -m venv .venv
      - run: .venv/bin/pip install -U pip wheel twine maturin
      - run: .venv/bin/pip install '.[tests]'
      - run: cargo target add armv7-unknown-linux-gnueabihf
      - run: .venv/bin/maturin build --no-sdist --release --strip --manylinux 2014 -i python3.9 --target armv7-unknown-linux-gnueabihf
      - run: .venv/bin/pip install konnoohmachi --no-index -f target/wheels
      # - run: .venv/bin/pytest
      # - run: .venv/bin/twine upload --non-interactive --skip-existing target/wheels/*

